% Function func_plot_colormaps
% Return colourmap for plots

% TO DO
% - choose cmap according to number of lines to plot?

function [cmap, cmap_axis] = func_plot_colormaps(data_name, multiplot, numPlots)
  if multiplot
    if numPlots <= 8
      cmap = ["#1b9e77", ...
        "#d95f02", ...
        "#7570b3", ...
        "#e7298a", ...
        "#66a61e", ...
        "#e6ab02", ...
        "#a6761d", ...
        "#666666"];      
    else
      cmap = [
        "#a6cee3", ...
        "#1f78b4", ...
        "#b2df8a", ...
        "#33a02c", ...
        "#fb9a99", ...
        "#e31a1c", ...
        "#fdbf6f", ...
        "#ff7f00", ...
        "#cab2d6", ...
        "#6a3d9a"];
    end
    cmap_axis = [];
  elseif data_name == "m_f_hist_animate"
    cmap  = [ 1,   1,   1;    % 0
              0.5, 0.5, 0.5;  % 1
              1,   0.5, 0;    % 2
              1,   0,   0;    % 3
              0,   0,   0];   % 4  
    cmap_axis = [0 4];
  else
    cmap = [];
    cmap_axis = [];
  end
end

